Abc.Northwind.MvcWebUI/Controllers/ProductController.cs
using Abc.Northwind.MvcWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Mvc.Northwind.Business.Abstract;

namespace Abc.Northwind.MvcWebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public IActionResult Index(int page = 1, int category = 0)
        {
            int pageSize = 10;
            var products = _productService.GetByCategory(category);
            ProductListViewModel model = new ProductListViewModel
            {
                Products = products.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                PageCount = (int)Math.Ceiling(products.Count / (double)pageSize),
                PageSize = pageSize,
                CurrentCategory = category,
                CurrentPage = page
            };

            return View(model);
        }
       

    }

}

Abc.Northwind.MvcWebUI/ViewComponents/CartSummaryViewComponent.cs
using Abc.Northwind.MvcWebUI.Models;
using Abc.Northwind.MvcWebUI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace Abc.Northwind.MvcWebUI.ViewComponents
{
    public class CartSummaryViewComponent : ViewComponent
    {
        ICartSessionService _cartSessionService;
        public CartSummaryViewComponent(ICartSessionService cartSessionService)
        {
            _cartSessionService = cartSessionService;
        }

        public ViewViewComponentResult Invoke()
        {
            var model = new CartSummaryViewModel
            {
                Cart = _cartSessionService.GetCart()
            };
            return View(model);
        }
    }
}

Abc.Northwind.MvcWebUI/ViewComponents/CategoryListViewComponent.cs
using Abc.Northwind.MvcWebUI.Models;
using Microsoft.AspNetCore.Mvc;
using Mvc.Northwind.Business.Abstract;

namespace Abc.Northwind.MvcWebUI.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),
                CurentCategory = Convert.ToInt32(HttpContext.Request.Query["category"])
            };

            return View(model);
        }
    }
}

Abc.Northwind.MvcWebUI/ViewComponents/UserSummaryViewComponent.cs
using Abc.Northwind.MvcWebUI.Models;
using Azure.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace Abc.Northwind.MvcWebUI.ViewComponents
{
    public class UserSummaryViewComponent:ViewComponent
    {
        public ViewViewComponentResult Invoke()
        {
            
            UserDetailsVievModel model = new UserDetailsVievModel
            {
               Username = HttpContext.User.Identity.Name,
            };
            return View(model);
        }
    }
}

Abc.Northwind.MvcWebUI/Views/Shared/_AdminLayout.cshtml
<html>
<head>
    <link href="\node_modules\bootstrap\dist\css\bootstrap.min.css" rel="stylesheet" />
    <script src="\node_modules\jquery\dist\jquery.min.js"></script>
    <script src="\node_modules\bootstrap\dist\js\bootstrap.bundle.min.js"></script>
    <script src="\node_modules\jquery-validation\dist\jquery.validate.min.js"></script>
    <script src="\node_modules\jquery-validation-unobtrusive\dist\jquery.validate.unobtrusive.min.js"></script>
    @*    <script src="\node_modules\bootstrap\dist\js\bootstrap.min.js"></script>
    *@
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                        <a class="navbar-brand" href="#">Northwind Admin Panel</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="Product">Product Store</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Dropdown
                                    </a>
                                    @await Component.InvokeAsync("UserSummary")
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <div class="row">
           
            <div class="col-md-12">
                @if (TempData["message"] != null)
                {
                    <div class="alert alert-info" role="alert">@TempData["message"]</div>
                }
                @RenderBody()
            </div>
        </div>
        
    </div>

</body>
</html>

Abc.Northwind.MvcWebUI/Views/Shared/_Layout.cshtml
<html>
<head>
    <link href="\node_modules\bootstrap\dist\css\bootstrap.min.css" rel="stylesheet" />
    <script src="\node_modules\jquery\dist\jquery.min.js"></script>
    <script src="\node_modules\bootstrap\dist\js\bootstrap.bundle.min.js"></script>
    <script src="\node_modules\jquery-validation\dist\jquery.validate.min.js"></script>
    <script src="\node_modules\jquery-validation-unobtrusive\dist\jquery.validate.unobtrusive.min.js"></script>
    @*    <script src="\node_modules\bootstrap\dist\js\bootstrap.min.js"></script>
    *@
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                        <a class="navbar-brand" href="#">Northwind</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Account" asp-action="Login">Admin</a>
                                </li>

                            </ul>
                            <ul class="navbar-nav">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Sepet
                                    </a>
                                    @await Component.InvokeAsync("CartSummary")
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @await Component.InvokeAsync("CategoryList")
            </div>
            <div class="col-md-10">
                @if (TempData["message"] != null)
                {
                    <div class="alert alert-info" role="alert">@TempData["message"]</div>
                }
                @RenderBody()
            </div>
        </div>
       
    </div>

</body>
</html>